[project]
name = "llms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.96.0",
    "datasets>=5.0.0",
    "dotenv>=0.9.9",
    "jinja2>=3.1.6",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "nest-asyncio>=1.6.0",
    "nltk>=3.9.4",
    "notebook>=7.5.6",
    "openai>=3.19.2",
    "pydantic>=2.13.2",
    "pydot>=4.0.1",
    "sentence-transformers>=5.4.1",
    "tqdm>=4.67.3",
    "typesafe-sdk>=0.7.1",
    "watermark>=2.6.0",
    "vllm>=0.31.0 ; sys_platform == 'linux'",
    "vllm-gguf-plugin>=0.0.5 ; sys_platform == 'linux'",
    "huggingface-hub>=1.27.0",
]
